int int_equal(int value);
char char_not_equal(char value);
long long_greater(long value);
int int_less_or_equal(int value);
int int_greater_or_equal(int value);
long long long_long_less(long value);
int is_even(int value);
int is_odd(int value);
int* give_me_a_pointer();
int* dont_give_me_a_pointer();
const char* ping();
const char* pong();
const char* hello();
const char* world();
float float_equal(float value);
double double_equal(double value);
float float_near(float value);
